
### Obtener todas las Peliculas
GET http://localhost:3080/film

### Obtener una Pelicula por su ID
GET http://localhost:3080/film/502

### Crear una Pelicula
POST http://localhost:3080/film
Content-Type: application/json

{
    "title": "ZORRujO ARK",
    "description": "A Intrepid Panorama of a Mad Scientist And a Boy who must Redeem a Boy in A Monastery",
    "release_year": 2005,
    "language_id": 1,
    "original_language_id": null,
    "rental_duration": "3",
    "rental_rate": "4.95",
    "length": 50,
    "replacement_cost": "17.99",
    "rating": "NC-17",
    "special_features": [
        "Deleted Scenes",
        "Behind the Scenes"
    ],
    "last_update": "2024-02-15 05:03:42"
}

### Editar una Pelicula
PUT http://localhost:3080/film/1019
Content-Type: application/json

{
    "title": "ZORRujddasO KRAK",
    "description": "A Intrepid Panorama of a Mad Scientist And a Boy who must Redeem a Boy in A Monastery",
    "release_year": 2005,
    "language_id": 1,
    "original_language_id": null,
    "rental_duration": "3",
    "rental_rate": "4.95",
    "length": 50,
    "replacement_cost": "17.99",
    "rating": "NC-17",
    "special_features": [
        "Deleted Scenes",
        "Behind the Scenes"
    ],
    "last_update": "2024-02-15 05:03:42"
}

### Eliminar una Pelicula
DELETE http://localhost:3080/film/502
