
### Obtener todas las peliculas
GET http://localhost:3080/film

###
GET http://localhost:3080/film/1000

###
POST http://localhost:3080/film
Content-Type: application/json;

{
    "film_id": 1001,
    "title": "ZORRO ARK",
    "description": "A Intrepid Panorama of a Mad Scientist And a Boy who must Redeem a Boy in A Monastery",
    "release_year": "2006",
    "language_id": 1,
    "original_language_id": null,
    "rental_duration": "3",
    "rental_rate": "4.99",
    "length": "50",
    "replacement_cost": "18.99",
    "rating": "NC-17",
    "last_update": "2025-12-28T04:03:42.000Z",
    "special_features": [
        "Deleted Scenes",
        "Behind the Scenes"
    ]
}

###
delete http://localhost:3080/film/995